### ISSUE TITLE
syslog_ng container incorrectly reports missing node with proteus label

### ISSUE THREAD

**Issue by jdavisclark** [siemonster/rancher-free#1]
> syslog-ng (Failed to allocate instance [container:1i1176]: Bad instance [container:1i1176] in state [stopping]: Allocation failed: needs host with label proteus: 1) 

I've got a node with `proteus:1` label on it. othere stuff is getting scheduled there just fine. Seems like more of a rancher issue than anything but...

**Comment by siemonster** [comment]
Can you try restarting the Proteus host, and follow up with a ticket on the forum if it is still an issue.
[https://siemonster.jiveon.com/](url)

**Comment by jdavisclark** [comment]
@siemonster It was something like that. I up killing and recreating my cluster for other reasons, and it was fine the second time around.
